#!/bin/bash
#$Id: dist-make,v 1.1 2005-09-11 20:05:31 mitch Exp $

set +e

VERSION=$( head -n 1 .version | sed s/^0+// )
VERSION=$(printf %04d $(( $VERSION + 1)))

rm -rf builddir

cvs update
mkdir -p builddir/grabcd-$VERSION/Grabcd
cp encode.pl grabcd.pl README scancd.pl builddir/grabcd-$VERSION
cp Grabcd/ReadConfig.pm builddir/grabcd-$VERSION/Grabcd
(
    cd builddir
    tar -czvf ../grabcd-$VERSION.tar.gz grabcd-$VERSION
)
rm -rf builddir
cp grabcd-$VERSION.tar.gz grabcd_$VERSION.orig.tar.gz

echo $VERSION > .version
