--- !ditz.rubyforge.org,2008-03-06/project 
name: grabcd
version: "0.4"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: grabcd
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0007"
  status: :released
  release_time: 2008-08-05 20:40:16.113635 Z
  log_events: 
  - - 2008-08-05 18:54:35.295874 Z
    - Christian Garbs <mitch@cgarbs.de>
    - created
    - ""
  - - 2008-08-05 20:40:16.113665 Z
    - Christian Garbs <mitch@cgarbs.de>
    - released
    - ""
