--- !ditz.rubyforge.org,2008-03-06/project 
name: grabcd
version: "0.4"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: grabcd
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0007"
  status: :released
  release_time: 2008-08-05 20:40:16.113635 Z
  log_events: 
  - - 2008-08-05 18:54:35.295874 Z
    - Christian Garbs <mitch@cgarbs.de>
    - created
    - ""
  - - 2008-08-05 20:40:16.113665 Z
    - Christian Garbs <mitch@cgarbs.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0008
  status: :released
  release_time: 2008-11-22 18:10:18.163727 Z
  log_events: 
  - - 2008-11-22 17:53:29.917590 Z
    - Christian Garbs <mitch@cgarbs.de>
    - created
    - ""
  - - 2008-11-22 18:10:18.163760 Z
    - Christian Garbs <mitch@cgarbs.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0009
  status: :released
  release_time: 2008-12-29 18:48:43.887555 Z
  log_events: 
  - - 2008-11-22 18:14:29.737849 Z
    - Christian Garbs <mitch@cgarbs.de>
    - created
    - ""
  - - 2008-12-29 18:48:43.887587 Z
    - Christian Garbs <mitch@cgarbs.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0010"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-12-29 18:54:50.444407 Z
    - Christian Garbs <mitch@cgarbs.de>
    - created
    - ""
